export const ItemTypes = {
  EMBEDDED: 'embedded',
  BLOCK: 'block',
  RANGE: 'range',
  DECLARATION: 'declaration',
  COMPARISON: 'comparison',
  VARIABLE: 'variable',
  KEY_VALUE: 'key_value',
  IF_NESTING: 'if_nesting',
  SWITCH: 'switch',
  FUNCTION_CALL: 'function_call',
  CONCAT: 'concat',
  DICT: 'dict',
  LIST: 'list',
  EMBEDDED_SENTENCE: 'embedded_sentence',
  NUMBER: 'number',
  STRING: 'string',
  BOOLEAN: 'boolean',
  NULL: 'null',
  ANUMERO: 'anumero',
  ACADENA: 'acadena',
  ALOGICO: 'alogico',
  ARGUMENT_LIST: 'argument_list',
};